# Site Setting
Titulo: Sumas literarias de la Edad Media
Creado por:
  Nombre: G. Tzite Reyes Vega
  Email: tzite_shadowdarkrai@hotmail.com
Descripción: "Conjunto de notas para entender que es una Suma Literaria/Filosofica y para que servían éstas en el Siglo XII.
